### ISSUE TITLE
I translated it into Simplified Chinese

### ISSUE THREAD

**Issue by ArchiDreamZ** [SnappyDragon64/Snuffles#3]
{
  "block.snuffles.snuffle_fluff": "魄罗绒毛",
  "block.snuffles.frosty_fluff": "霜冻的绒毛",
  "block.snuffles.snuffle_fluff_carpet": "魄罗绒毛地毯",
  "block.snuffles.frosty_fluff_carpet": "霜冻的绒毛地毯",

  "item.snuffles.snuffle_spawn_egg": "魄罗刷怪蛋",

  "entity.snuffles.snuffle": "魄罗",

  "snuffles.subtitles.block.frosty_fluff.thaw": "绒毛融化",

  "snuffles.subtitles.entity.snuffle.ambient": "魄罗：嗅嗅",
  "snuffles.subtitles.entity.snuffle.death": "魄罗：死亡",
  "snuffles.subtitles.entity.snuffle.eat": "魄罗：进食",
  "snuffles.subtitles.entity.snuffle.hurt": "魄罗：受伤",
  "snuffles.subtitles.entity.snuffle.shake": "魄罗：抖动",
  "snuffles.subtitles.entity.snuffle.step": "魄罗：脚步声",
  "snuffles.subtitles.entity.snuffle.style": "魄罗：粘液球压扁",
  "snuffles.subtitles.entity.snuffle.thaw": "魄罗：融化"
}

**Comment by SnappyDragon64** [comment]
PR merged
